version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: cadastro-ninjas
    environment:
      POSTGRES_DB: cadastro-ninjas
      POSTGRES_USER:  ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5431:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d cadastro-ninjas"]
      interval: 5s
      timeout: 5s
      retries: 5